name: SimpleRestart
main: com.hamaluik.SimpleRestart.SimpleRestart
version: 2.0.0
api-version: 1.14

authors:
  - "FuzzyWuzzie"
  - "THExSYSTEM"
  - "Pieter12345/woesh0007"
  - "Ecconia"
website: "https://github.com/Pieter12345/SimpleRestart"

commands:
   restart:
      description: restart the server!
      usage: |
            usage:
                /restart now
   reboot:
      description: restart the server!
      usage: |
            usage:
                /reboot now
   memory:
      description: gives memory usage information
      usage: |
            usage:
                /memory