name: SimpleRestart
main: com.hamaluik.SimpleRestart.SimpleRestart
version: 2.0.0
api-version: 1.14

authors:
  - "FuzzyWuzzie"
  - "THExSYSTEM"
  - "Pieter12345/woesh0007"
  - "Ecconia"
website: "https://github.com/Pieter12345/SimpleRestart"

commands:
   restart:
     aliases: reboot
     permission: simplerestart.restart;simplerestart.time
     description: Command to control the scheduled restart.
   memory:
      permission: simplerestart.memory
      description: Gives server memory usage information.
